---
- name: Reset cluster
  hosts: k8s_cluster

  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  - name: reset k8s cluster
    ansible.builtin.shell: |
      kubeadm reset --force
    ignore_errors: yes
    become: yes    

#  - name: Disable keepalived and haproxy services
#    when: 
#      - ha_cluster_virtual_ip is defined
#      - ha_cluster_virtual_ip != ""
#      - inventory_hostname in groups['k8s_masters']
#    service:
#      name: "{{ item }}"
#      state: stopped
#      enabled: no
#    with_items:
#      - keepalived
#      - haproxy
#    ignore_errors: yes
  
#  - name: Uninstall HA packages RedHat
#    when: 
#      - ha_cluster_virtual_ip is defined 
#      - ha_cluster_virtual_ip != ""
#      - inventory_hostname in groups['k8s_masters']
#      - ansible_os_family == "RedHat"
#    dnf:
#      name:
#        - keepalived
#        - haproxy
#      state: absent
  
  - name: Uninstall Kubernetes packages RedHat
    dnf:
      name:
        - kubectl
        - kubeadm
        - kubelet
        - podman
        - crun
        - cri-o
        - iproute-tc
        - bash-completion
        - jq
      state: absent
    become: yes
