---
## cilium

- name: copy cilium manifest
  template:
    src: cilium-init.yaml
    dest: /etc/kubernetes/cilium-init.yaml
  become: yes

- name: add cilium chart repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io/"

- name: deploy cilium chart with values
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_version }}"
    release_namespace: kube-system
    values_files:
      - /etc/kubernetes/cilium-init.yaml
