---
## init first node

- name: init first control plane
  include_tasks: init-cluster.yaml
  when: inventory_hostname == groups['k8s_masters'][0]

## cilium

- name: cilium install 
  include_tasks: cilium.yaml
  when: inventory_hostname == groups['k8s_masters'][0]

## nodelocaldns

- name: install nodelocaldns
  include_tasks: nodelocaldns.yaml
  when: inventory_hostname == groups['k8s_masters'][0]

#- name: Wait for coredns started
#  shell:
#    cmd: "kubectl -n kube-system get svc kube-dns -o jsonpath='{.spec.clusterIP}'"
#  changed_when: false
#  check_mode: false
#  register: result
#  until: result.rc == 0
#  retries: 10 
#  delay: 30


# Nodelocaldns

#- name: Get coredns service IP address
#  shell: kubectl -n kube-system get svc kube-dns -o jsonpath='{.spec.clusterIP}'
#  register: dns_ip

#- set_fact: 
#    coredns_ip: "{{ dns_ip.stdout }}"

# Calico
# - name: Check namespace tigera-operator
#   shell:
#     cmd: "kubectl get ns tigera-operator"
#   changed_when: false
#   check_mode: false
#   register: ns_result
#   until: ns_result.rc == 0
#   retries: 10 
#   delay: 30

#- name: Check for installed tigera-operator
#  shell: kubectl get ns tigera-operator
#  register: tigera_operator_out
#  ignore_errors: yes
