---
# 1-st control node
- name: check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- meta: end_play
  when: kubeadm_ca.stat.exists

- name: create /etc/kubernetes directory
  file:
    path: /etc/kubernetes
    state: directory

- name: copy kubeadm-config.yaml
  template:
    src: init-config.yaml
    dest: /etc/kubernetes/kubeadm-config.yaml
  become: yes

- name: Init master control node
  shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  register: kubeadm_init
  become: yes 

- name: Add directory for config file
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
  become: yes

- name: copy config file
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  become: yes

## cilium
- name: Copy cilium manifest
  template:
    src: cilium-init.yaml
    dest: /etc/kubernetes/cilium-init.yaml



#- name: Wait for coredns started
#  shell:
#    cmd: "kubectl -n kube-system get svc kube-dns -o jsonpath='{.spec.clusterIP}'"
#  changed_when: false
#  check_mode: false
#  register: result
#  until: result.rc == 0
#  retries: 10 
#  delay: 30


# Nodelocaldns

#- name: Get coredns service IP address
#  shell: kubectl -n kube-system get svc kube-dns -o jsonpath='{.spec.clusterIP}'
#  register: dns_ip

#- set_fact: 
#    coredns_ip: "{{ dns_ip.stdout }}"

#- name: Copy nodelocaldns manifest
#  template:
#    src: nodelocaldns-daemonset.j2
#    dest: /etc/kubernetes/nodelocaldns-daemonset.yaml

#- name: Deploy nodelocaldns
#  shell: kubectl apply -f /etc/kubernetes/nodelocaldns-daemonset.yaml

# Calico
# - name: Check namespace tigera-operator
#   shell:
#     cmd: "kubectl get ns tigera-operator"
#   changed_when: false
#   check_mode: false
#   register: ns_result
#   until: ns_result.rc == 0
#   retries: 10 
#   delay: 30

#- name: Check for installed tigera-operator
#  shell: kubectl get ns tigera-operator
#  register: tigera_operator_out
#  ignore_errors: yes

#- name: Install tigera-operator
#  when: tigera_operator_out.rc == 1
#  shell: "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/{{ tigera_operator_version }}/manifests/tigera-operator.yaml"

#- name: Copy calico-install.yaml
#  template:
#    src: calico-install.j2
#    dest: /etc/kubernetes/calico-install.yaml

#- name: Install Calico
#  shell: kubectl apply -f /etc/kubernetes/calico-install.yaml

# Почему то в 1.25 на AlmaLinux 8 не ставится enabled
#- name: Kubelet enable
#  service:
#    name: kubelet
#    state: started
#    enabled: yes
